### ISSUE TITLE
Repository not quite compatible with haxelib

### ISSUE THREAD

**Issue by ProG4mr** [Simn/hxparse#29]
When using haxelib, its frequent to switch between haxelib and git versions.

Problem with hxparse atm, is that it uses directory src as the haxelib root directory.

Using ```haxelib set hxparse git```, does not work, one needs to set a dev version and manually set the directory to ....../libs/hxparse/git/src

Just something to keep in mind, a solution is simply to put src dir contents on the top of the repository.

**Comment by ProG4mr** [comment]
Nevermind, many other libs have the same problem anyway.

**Comment by Simn** [comment]
Actually I think we should address that. The haxelib.json file should not be in the src directory anyway.

I forget how to set this up the right way, do you want to fix it and send a pull request?

**Comment by ProG4mr** [comment]
Sure, think the right way to do it is to send haxelib.json to the top of the repo and add the entry: ```"classPath":"src"``` to it, I'll try it soon.

**Comment by Simn** [comment]
Sounds about right, thanks!
