### ISSUE TITLE
Fallthrough behaviour in Parser

### ISSUE THREAD

**Issue by 0b1kn00b** [Simn/hxparse#31]
I looks like when you have a match on the first token, and a failure on following tokens in the same case, any following cases in the original pattern match are ignored. Is this expected behaviour?

```
case [TLParen,TAtom(UnboundSym('defun')), sym = symbol(), xs = params(), xprs = sexpr(), TRParen] : Defun(sym,xs,xprs); //fail
case _                                                                                            : SE(sexpr()); //nothing
```

**Comment by Simn** [comment]
Yes, that's how stream parsing works. See https://github.com/Simn/hxparse/wiki/Writing-a-Parser#parsing-rules
