### ISSUE TITLE
haxelib release update

### ISSUE THREAD

**Issue by underscorediscovery** [Simn/hxparse#33]
Please release a versioned update on haxelib. 

I've been using hxparse (it's wonderfully easy to get into) but until there is a haxelib update for the year+ of updates and haxe 3.2 release changes there is no way I can share this with any users comfortably.

I think I saw @fussybeaver and @ProG4mr having the same thoughts.

**Comment by Simn** [comment]
I would love to but https://github.com/HaxeFoundation/haxelib/issues/223#issuecomment-112812075 still happens.

**Comment by underscorediscovery** [comment]
Aha, that's quite unhelpful.
I'm glad there is the desire though! 

I'll keep an eye out for it, thanks for the info

**Comment by andyli** [comment]
I would like to see a new release of it too. The blocking haxelib issue should has been fixed.

**Comment by Atry** [comment]
@Simn I guess https://github.com/HaxeFoundation/haxelib/issues/223#issuecomment-112812075 have been resolved for a long time

**Comment by Simn** [comment]
Can someone check if the currently development branch works with Haxe 3.1.3? I'm never sure how to deal with this kind of dependency. That's also the reason I didn't accept #35 yet.

**Comment by Simn** [comment]
I have just released hxparse to haxelib as version 4.0.0 as I'm pretty sure it's not compatible with 3.1.3.

**Comment by underscorediscovery** [comment]
Nice! You could also make a tag at a revision in history that works with 3.1.3 if people were looking for it.

**Comment by Simn** [comment]
Sure, if I find out which revision that is.

**Comment by underscorediscovery** [comment]
I might have a vm with 3.1.3, I'll see if I can find it over the weekend since I had a number of hxparse projects alongside it there.
