### ISSUE TITLE
please expose the AST in the api. 

### ISSUE THREAD

**Issue by kobi2187** [Simn/hxparse#39]
Hello
Is there a way to expose the AST or whatever tree is built, when using this Parser?
I couldn't find this in the api or docs.
Thanks.

**Comment by Simn** [comment]
I'm not sure what you're asking for. The AST which is parsed is defined by the user.

**Comment by kobi2187** [comment]
Hi Simon,
thanks for the reply
I'm new to parsing.
let's say I want to take an xml file and transform it to yaml file or 
json file.
can I get this intermediate state, the parse tree (or abstract syntax 
tree), so I can create backends from this state?
assuming hxparse is not "just" a validator, can I get the "internal" 
state or tree?
That was my meaning
Thanks, kobi

On 28/11/15 11:00, Simon Krajewski wrote:
>
> I'm not sure what you're asking for. The AST which is parsed is 
> defined by the user.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Simn/hxparse/issues/39#issuecomment-160265364>.
>

-- 
http://www.faluninfo.net

**Comment by Simn** [comment]
hxparse is a parser generator, it doesn't know what an AST even is. That's totally up to the user to define, so there's really nothing to expose here.
