### ISSUE TITLE
usage from macros

### ISSUE THREAD

**Issue by underscorediscovery** [Simn/hxparse#43]
Is it feasible to run a parser from a `macro` context?
I _am_ busy testing this but asking may prove quicker and more definitive.

I had this error come up when attempting to run a parser at compile time:
`haxelib/hxparse/4,0,0/src/hxparse/Parser.hx:154: lines 154-161 : A generic class can't have static fields`

By hacking around a bit further I managed to get more errors along the lines of not being allowed to use @:build from a macro, which given how hxparse works it might not make sense to try?

Thanks!

**Comment by Simn** [comment]
Yes that's gonna be an issue I'm afraid. Haxe's macro-in-macro support is a bit limited to say the least.

**Comment by underscorediscovery** [comment]
Understandable! For compile time validation I'll use a prebuilt version instead. Thanks for the quick reply
