### ISSUE TITLE
Is it possible to use this library at compile-time?

### ISSUE THREAD

**Issue by FrancisBourre** [Simn/hxparse#47]
Hi,

thanks for the amazing work!

Just a quick question, is there a way to use this library from an expression macro?

**Comment by Simn** [comment]
I completely missed this question, sorry about that!

Unfortunately, it's not easily possible to use this library at compile-time because that would lead to macro-in-macro situations, which the Haxe compiler currently doesn't support.

**Comment by FrancisBourre** [comment]
Thanks for the answer @Simn 
Btw, I'm interested to find any nice haxe library for parsing custom DSLs (at compile time and runtime). Have you got any recommendation?

**Comment by nadako** [comment]
I thought hxparse could be used in macros, it's just RuleBuilder and other sugar classes can't be.

**Comment by Simn** [comment]
Hmm, technically yes. I remembered that I added Parser.parse for this which can be used instead of the `@:build` macro. It's obviously less convenient, but there are chances it works.
