### ISSUE TITLE
Exponent on JSON parser example

### ISSUE THREAD

**Issue by hughsando** [Simn/hxparse#49]
I think regex should be:
"-?(([1-9][0-9]*)|0)(.[0-9]+)?([eE][\\+\\-]?[0-9]+)?" => TNumber(lexer.current),

ie "[0-9]+" not "[0-9]?"

**Comment by Simn** [comment]
I guess technically it should even be `[1-9][0-9]*` but oh well.

**Comment by hughsando** [comment]
Actually, I have some code (from c++ I think) that does 1.1e-006

**Comment by Simn** [comment]
Right, so all is good now.
