### ISSUE TITLE
[REQUEST] An example for parsing simple dynamic language like 'Kaleidoscope'

### ISSUE THREAD

**Issue by darmie** [Simn/hxparse#52]
I am very curious about writing parsers and compilers. I come from a background of using PEGs to generate parsers. So the concept of writing a parser by hand is entirely new to me.  I love Haxe and I want to experiment with parsers using hxparse. I have taken a look at `haxeparser` library as an implementation guide for a full programming language parsing, but things got complex has it seems to depend on inbuilt Haxe macros for tokenizing expressions. 

I'll be glad if there is a simple example or tutorial that explains step-by-step how to parse a simple dynamic language like the `Kaleidoscope` example. 

Thank you!!

**Comment by Simn** [comment]
There are some basic examples here: https://github.com/Simn/hxparse/tree/master/test

I currently don't have plans to extend the documentation and examples of this library, but I would of course accept pull requests that do so!

**Comment by darmie** [comment]
Yes I already saw those examples. I was hoping to find one for an actual programming language. 

Thanks.
